<?php

return array
    (
    // Add first time icon
    array
        (
        ':)' => '__smile.png__:)__Smile__',
        ':(' => '__sad.png__:(__Sad__',
        ':D' => '__smile-big.png__:D__Big Smile__',
        ';)' => '__wink.png__;)__Wink__',
        ':-O' => '__shock.png__:-O__Shock__',
        ':P' => '__tongue.png__:P__Tongue__',
        '(H)' => '__glasses-cool.png__(H)__Glasses Cool__',
        ':@' => '__angry.png__:@__Angry__',
        ':$' => '__embarrassed.png__:$__Embarrassed__',
        ':S' => '__confused.png__:S__Confused__',
        ":'(" => "__crying.png__:'(__Crying__",
        'I-)' => '__sleepy.png__I-)__Sleepy__',
        '^:)^' => '__worship.png__^:)^__Worship__',
        ':-W' => '__waiting.png__:-W__Waiting__',
        '=;' => '__bye.png__=;__Bye__',
        '[-X' => '__shame.png__[-X__Shame__',
        ':-X' => '__shut-mouth.png__:-X__Shut Mouth__',
        ':|' => '__neutral.png__:|__Neutral__',
        '(6)' => '__devil.png__(6)__Devil__',
        '(A)' => '__angel.png__(A)__Angel__',
        '(L)' => '__love.png__(L)__Love__',
        '(U)' => '__love-over.png__(U)__Love Over__',
        '(@)' => '__cat.png__(@)__Cat__',
        '(&)' => '__dog.png__(&)__Dog__',
        '(S)' => '__moon.png__(S)__Moon__',
        '(*)' => '__star.png__(*)__Star__',
        '(~)' => '__film.png__(~)__Film__',
        '(8)' => '__musical-note.png__(8)__Note Musical__',
        '(E)' => '__mail.png__(E)__Mail__',
        '(F)' => '__rose.png__(F)__Rose__',
        '(W)' => '__rose-dead.png__(W)__Dead Rose__',
        '(O)' => '__clock.png__(O)__Clock__',
        '(K)' => '__kiss.png__(K)__Kiss__',
        '(G)' => '__present.png__(G)__Present__',
        '(^)' => '__cake.png__(^)__Cake__',
        '(P)' => '__camera.png__(P)__Camera__',
        '(I)' => '__lamp.png__(I)__Lamp__',
        '(C)' => '__coffee.png__(C)__Coffee__',
        '(T)' => '__phone.png__(T)__Phone__',
        '({)' => '__hug-left.png__({)__Left Hug__',
        '(})' => '__hug-right.png__(})__Right Hug__',
        '(B)' => '__beer.png__(B)__Beer__',
        '(D)' => '__drink.png__(D)__Drink__',
        '(Z)' => '__boy.png__(Z)__Boy__',
        '(X)' => '__girl.png__(X)__Girl__',
        '(Y)' => '__good.png__(Y)__Good__',
        '(N)' => '__bad.png__(N)__Bad__',
        ':[' => '__vampire.png__:[__Vampire__',
        '(nah)' => '__goat.png__(nah)__Goat__',
        '(#)' => '__sun.png__(#)__Sun__',
        '(R)' => '__rainbow.png__(R)__Rainbow__',
        ':-#' => '__quiet.png__:-#__Quiet__',
        '8o|' => '__teeth.png__8o|__Teeth__',
        '8-|' => '__glasses-nerdy.png__8-|__Glasses Nerdy__',
        '^o)' => '__sarcastic.png__^o)__Sarcastic__',
        ':-*' => '__secret.png__:-*__Secret__',
        '+o(' => '__sick.png__+o(__Sick__',
        '(sn)' => '__snail.png__(sn)__Snail__',
        '(tu)' => '__turtle.png__(tu)__Turtle__',
        '(pl)' => '__plate.png__(pl)__Plate__',
        '(||)' => '__bowl.png__(||)__Bowl__',
        '(pi)' => '__pizza.png__(pi)__Pizza__',
        '(so)' => '__soccerball.png__(so)__Soccerball__',
        '(au)' => '__car.png__(au)__Car__',
        '(ap)' => '__airplane.png__(ap)__Airplane__',
        '(um)' => '__umbrella.png__(um)__Umbrella__',
        '(ip)' => '__island.png__(ip)__Island__',
        '(co)' => '__computer.png__(co)__Computer__',
        '(mp)' => '__mobile.png__(mp)__Mobile__',
        '(brb)' => '__brb.png__(brb)__Brb__',
        '(st)' => '__rain.png__(st)__Rain__',
        '(h5)' => '__highfive.png__(h5)__Highfive__',
        '(co)' => '__coins.png__(co)__Coins__',
        '(bah)' => '__sheep.png__(bah)__Sheep__',
        ':^)' => '__dont-know.png__:^)__Dont Know__',
        '*-)' => '__thinking.png__*-)__Thinking__',
        '(li)' => '__thunder.png__(li)__Thunder__',
        '<:o)' => '__party.png__<:o)__Party__',
        '8-)' => '__eyeroll.png__8-)__Eyeroll__',
        '|-)' => '__yawn.png__|-)__Yawn__',
        ':-(|)' => '__monkey.png__:-(|)__Monkey__',
    ),
    // Add same icon again with difirent symbol 
    array
        (
        ':-)' => '__smile.png__:-)__Smile__',
        ':-(' => '__sad.png__:-(__Sad__',
        ':d' => '__smile-big.png__:d__Big Smile__',
        ':-D' => '__smile-big.png__:-D__Big Smile__',
        ':-d' => '__smile-big.png__:-d__Big Smile__',
        ':-w' => '__waiting.png__:-w__Waiting__',
        '[-x' => '__shame.png__[-x__Shame__',
        ';-)' => '__wink.png__;-)__Wink__',
        ':-o' => '__shock.png__:-o__Shock__',
        ':p' => '__tongue.png__:p__Tongue__',
        '(h)' => '__glasses-cool.png__(h)__Glasses Cool__',
        ':-@' => '__angry.png__:-@__Angry__',
        ':-$' => '__embarrassed.png__:-$__Embarrassed__',
        ':s' => '__confused.png__:s__Confused__',
        ':-S' => '__crying.png__:s__Crying__',
        'i-)' => '__sleepy.png__i-)__Sleepy__',
        ':-|' => '__neutral.png__:-|__Neutral__',
        '(a)' => '__angel.png__(a)__Angel__',
        '(l)' => '__love.png__(l)__Love__',
        '(u)' => '__love-over.png__(u)__Love Over__',
        '(e)' => '__mail.png__(e)__Mail__',
        '(f)' => '__rose.png__(f)__Rose__',
        '(w)' => '__rose-dead.png__(w)__Dead Rose__',
        '(o)' => '__clock.png__(o)__Clock__',
        '(k)' => '__kiss.png__(k)__Kiss__',
        '(g)' => '__present.png__(g)__Present__',
        '(p)' => '__camera.png__(p)__Camera__',
        '(i)' => '__lamp.png__(i)__Lamp__',
        '(c)' => '__coffee.png__(c)__Coffee__',
        '(t)' => '__phone.png__(t)__Phone__',
        '(b)' => '__beer.png__(b)__Beer__',
        '(d)' => '__drink.png__(d)__Drink__',
        '(z)' => '__boy.png__(z)__Boy__',
        '(x)' => '__girl.png__(x)__Girl__',
        '(y)' => '__good.png__(y)__Good__',
        '(n)' => '__bad.png__(n)__Bad__',
        ':-[' => '__vampire.png__:-[__Vampire__',
        '(r)' => '__rainbow.png__(r)__Rainbow__',
    )
);
?>